import { colors, radii, typography } from "@fenchem-lp/ui/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const sharedStyles = stylex.create({
  techLabel: {
    fontFamily: typography.tech,
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.26em",
    color: colors.mute600,
  },
  techLabelDark: {
    fontFamily: typography.tech,
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.26em",
    color: colors.brandGreen400,
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  ruleLine: {
    display: "block",
    height: 1,
    width: "100%",
    transformOrigin: "left",
    backgroundColor: colors.line,
    border: "none",
    margin: 0,
    padding: 0,
  },
  ruleLineDark: {
    display: "block",
    height: 1,
    width: "100%",
    transformOrigin: "left",
    backgroundColor: "color-mix(in oklch, var(--color-cream) 15%, transparent)",
    border: "none",
    margin: 0,
    padding: 0,
  },
  primaryCta: {
    display: "inline-flex",
    minHeight: "2.75rem",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.625rem",
    borderRadius: radii.full,
    backgroundColor: {
      default: colors.brandGreen500,
      ":hover": colors.brandGreen400,
    },
    paddingInline: "1.75rem",
    paddingBlock: "0.875rem",
    fontFamily: typography.body,
    fontWeight: 600,
    color: colors.brandGreen950,
    fontSize: "0.875rem",
    textDecoration: "none",
    transition: "background-color 200ms ease, transform 200ms ease",
    cursor: "pointer",
    outline: {
      ":focus-visible": `2px solid ${colors.cream}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
    ":active": {
      transform: "scale(0.98)",
    },
  },
  secondaryCta: {
    display: "inline-flex",
    minHeight: "2.75rem",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.625rem",
    borderRadius: radii.full,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: "color-mix(in oklch, var(--color-cream) 30%, transparent)",
      ":hover": "color-mix(in oklch, var(--color-cream) 70%, transparent)",
    },
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in oklch, var(--color-cream) 10%, transparent)",
    },
    paddingInline: "1.75rem",
    paddingBlock: "0.875rem",
    fontFamily: typography.body,
    fontWeight: 600,
    color: colors.cream,
    fontSize: "0.875rem",
    textDecoration: "none",
    transition: "border-color 200ms ease, background-color 200ms ease, transform 200ms ease",
    cursor: "pointer",
    outline: {
      ":focus-visible": `2px solid ${colors.brandGreen300}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
    ":active": {
      transform: "scale(0.98)",
    },
  },
});
