#!/usr/bin/env node
// Phase 0 perf baseline orchestrator (issue #3: "Migrate styling from Tailwind CSS v4
// to StyleX with exact visual retention").
//
// Runs build-time, asset-size, and local cold-start measurement, then appends one row
// to perf/log.json and regenerates perf/log.md from it. The same script captures both
// columns of the comparison — run with --stack=stylex once that migration phase lands,
// so the two columns are produced by identical methodology (issue requirement #1).
//
// NOT covered by this script (separate follow-up — needs a live deployment decision):
//   - Cloudflare deployed cold-start probe + Server-Timing Worker share (issue item 42)
//   - Real-user web-vitals/RUM beacon on the deployed site (issue item 43)
// See perf/README.md.
//
// Usage:
//   node perf/run.mjs [--stack=tailwind] [--build-runs=5] [--build-warmup=1]
//                      [--coldstart-runs=5] [--skip-full=true]

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

import { measureFull, measureWeb } from "./measure-build.mjs";
import { measureAssets } from "./measure-assets.mjs";
import { measureColdstart } from "./measure-coldstart.mjs";
import { fmtMs, fmtKB, parseArgs } from "./lib/util.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const LOG_JSON = join(ROOT, "perf/log.json");
const LOG_MD = join(ROOT, "perf/log.md");

function gitInfo() {
  try {
    const commit = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: ROOT })
      .toString()
      .trim();
    const branch = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd: ROOT })
      .toString()
      .trim();
    const dirty =
      execFileSync("git", ["status", "--porcelain"], { cwd: ROOT }).toString().trim().length > 0;
    return { commit, branch, dirty };
  } catch {
    return { commit: "unknown", branch: "unknown", dirty: null };
  }
}

function renderMarkdown(log) {
  const header = `# Perf log — Tailwind vs StyleX

Baseline + ongoing measurements for [issue #3](https://github.com/fpcMotif/fenchem-lp/issues/3)
(Migrate styling from Tailwind CSS v4 to StyleX with exact visual retention).

Generated by \`perf/run.mjs\` — one row per run. Do not hand-edit; re-run the script instead.
Full source data (including per-run cold-start samples) lives in \`perf/log.json\`.

**Tool boundary — never mixed** (per issue #3): \`hyperfine\` measures compile wall-time
only · Playwright/\`PerformanceObserver\` measures local cold-start paint timings only ·
deployed Cloudflare cold-start + real-user web-vitals are a separate follow-up (the
\`--url\` mode on \`measure-coldstart.mjs\` covers synthetic deployed probing; a
\`Server-Timing\` Worker-share header and real-user RUM are not wired — see
\`perf/README.md\`).

Cold-start columns show **median / p75** — p75 is the percentile Core Web Vitals
actually grades on. \`coldstart.method\` in \`log.json\` distinguishes rows measured
before vs. after the LCP-stabilization-poll fix (the earlier fixed-500ms-post-load read
undercounted LCP on this site's animated hero); mixed-method rows aren't a fair diff.

| Date | Stack | Commit | Full build (cold, n=1) | Web bundle (${log[0]?.build?.web?.tool ?? "hyperfine"}) | CSS raw/gzip | JS raw/gzip | TTFB med/p75 | FCP med/p75 | LCP med/p75 | CLS med/p75 |
|---|---|---|---|---|---|---|---|---|---|---|
`;
  const rows = log
    .map((e) => {
      const css = `${fmtKB(e.assets.buckets.css.raw)} / ${fmtKB(e.assets.buckets.css.gzip)}`;
      const js = `${fmtKB(e.assets.buckets.js.raw)} / ${fmtKB(e.assets.buckets.js.gzip)}`;
      const commit = `${e.git.commit}${e.git.dirty ? "*" : ""}`;
      const c = e.coldstart;
      const pair = (medianKey, p75Key, fmt) => `${fmt(c[medianKey])} / ${fmt(c[p75Key])}`;
      const fmtCls = (v) => (v == null ? "—" : v.toFixed(3));
      return (
        `| ${e.date.slice(0, 10)} | ${e.stack} | ${commit} | ${fmtMs(e.build.full?.mean_ms)} | ` +
        `${fmtMs(e.build.web.mean_ms)} | ${css} | ${js} | ${pair("ttfb_median", "ttfb_p75", fmtMs)} | ` +
        `${pair("fcp_median", "fcp_p75", fmtMs)} | ${pair("lcp_median", "lcp_p75", fmtMs)} | ` +
        `${pair("cls_median", "cls_p75", fmtCls)} |`
      );
    })
    .join("\n");
  return `${header + rows}\n`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2), {
    stack: "tailwind",
    buildRuns: 5,
    buildWarmup: 1,
    coldstartRuns: 7,
    skipFull: false,
  });
  const startedAt = new Date().toISOString();

  console.log(`\n=== Phase 0 perf baseline — stack: ${args.stack} ===`);

  const full = args.skipFull ? null : measureFull();
  const web = measureWeb({ runs: args.buildRuns, warmup: args.buildWarmup });
  const assets = measureAssets();
  const coldstart = await measureColdstart({ runs: args.coldstartRuns });

  const entry = {
    date: startedAt,
    stack: args.stack,
    git: gitInfo(),
    node: process.version,
    platform: `${process.platform}/${process.arch}`,
    build: { full, web },
    assets,
    coldstart,
  };

  const log = existsSync(LOG_JSON) ? JSON.parse(readFileSync(LOG_JSON, "utf8")) : [];
  log.push(entry);
  writeFileSync(LOG_JSON, `${JSON.stringify(log, null, 2)}\n`);
  writeFileSync(LOG_MD, renderMarkdown(log));

  console.log("\n=== Summary ===");
  console.log(`Full monorepo build (cold, 1 run):        ${fmtMs(full?.mean_ms)}`);
  console.log(
    `Web bundle step (${web.tool}, n=${web.runs}, warmup=${web.warmup}): ${fmtMs(web.mean_ms)} ± ${fmtMs(web.stddev_ms)}`,
  );
  console.log(
    `CSS payload:  ${fmtKB(assets.buckets.css.raw)} raw / ${fmtKB(assets.buckets.css.gzip)} gzip`,
  );
  console.log(
    `JS payload:   ${fmtKB(assets.buckets.js.raw)} raw / ${fmtKB(assets.buckets.js.gzip)} gzip`,
  );
  console.log(
    `Cold start (n=${coldstart.runs}, median/p75): ` +
      `TTFB ${fmtMs(coldstart.ttfb_median)}/${fmtMs(coldstart.ttfb_p75)} · ` +
      `FCP ${fmtMs(coldstart.fcp_median)}/${fmtMs(coldstart.fcp_p75)} · ` +
      `LCP ${fmtMs(coldstart.lcp_median)}/${fmtMs(coldstart.lcp_p75)} · ` +
      `CLS ${coldstart.cls_median?.toFixed(3)}/${coldstart.cls_p75?.toFixed(3)}`,
  );
  console.log(`\nAppended to perf/log.json and regenerated perf/log.md`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
