// Perf log recording and markdown rendering with framework dimension enforcement.
// Cross-framework delta calculations are strictly prohibited.

import { fmtKB, fmtMs } from "./util.mjs";

export function validateFrameworkDelta(entryA, entryB) {
  if (!entryA || !entryB) {
    throw new Error("Cannot compute delta on undefined entries");
  }
  const fwA = entryA.framework || "unknown";
  const fwB = entryB.framework || "unknown";
  if (fwA !== fwB) {
    throw new Error(
      `Cross-framework delta calculation is invalid: cannot compare "${fwA}" with "${fwB}"`,
    );
  }
}

export function computeDelta(baseEntry, nextEntry) {
  validateFrameworkDelta(baseEntry, nextEntry);
  const baseRaw = baseEntry.assets?.total?.raw ?? 0;
  const nextRaw = nextEntry.assets?.total?.raw ?? 0;
  const baseGzip = baseEntry.assets?.total?.gzip ?? 0;
  const nextGzip = nextEntry.assets?.total?.gzip ?? 0;
  const baseBrotli = baseEntry.assets?.total?.brotli ?? 0;
  const nextBrotli = nextEntry.assets?.total?.brotli ?? 0;

  const baseBuild = baseEntry.build?.web?.mean_ms ?? baseEntry.build?.full?.mean_ms ?? 0;
  const nextBuild = nextEntry.build?.web?.mean_ms ?? nextEntry.build?.full?.mean_ms ?? 0;

  return {
    raw_diff_bytes: nextRaw - baseRaw,
    gzip_diff_bytes: nextGzip - baseGzip,
    brotli_diff_bytes: nextBrotli - baseBrotli,
    build_diff_ms: nextBuild - baseBuild,
  };
}

export function renderMarkdownLog(log = []) {
  const header = `# Perf log — TanStack Start vs Remix v3 & Styling Baselines

Generated by \`perf/run.mjs\` — one row per run. Do not hand-edit; re-run the script instead.
Full source data lives in \`perf/log.json\`.

**Methodology Rules**:
1. **Framework Dimension — Never Mixed**: Comparison deltas may only be drawn between rows sharing the exact same \`framework\` value. Cross-framework deltas are prohibited.
2. **Build Attribution**: Includes per-phase traces and per-chunk/module byte metrics across raw, gzip, and brotli.
3. **Cold-start**: Displays median / p75 percentiles.

| Date | Framework | Stack | Commit | Full build (cold) | Web bundle | CSS (raw/gz/br) | JS (raw/gz/br) | Total (raw/gz/br) | TTFB med/p75 | FCP med/p75 | LCP med/p75 | CLS med/p75 |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
`;

  const rows = log
    .map((e) => {
      const b = e.assets?.buckets || {
        css: { raw: 0, gzip: 0, brotli: 0 },
        js: { raw: 0, gzip: 0, brotli: 0 },
      };
      const t = e.assets?.total || { raw: 0, gzip: 0, brotli: 0 };
      const css = `${fmtKB(b.css.raw)} / ${fmtKB(b.css.gzip)} / ${fmtKB(b.css.brotli)}`;
      const js = `${fmtKB(b.js.raw)} / ${fmtKB(b.js.gzip)} / ${fmtKB(b.js.brotli)}`;
      const total = `${fmtKB(t.raw)} / ${fmtKB(t.gzip)} / ${fmtKB(t.brotli)}`;
      const commit = `${e.git?.commit ?? "—"}${e.git?.dirty ? "*" : ""}`;
      const c = e.coldstart || {};
      const pair = (medianKey, p75Key, fmt) =>
        c[medianKey] != null && c[p75Key] != null
          ? `${fmt(c[medianKey])} / ${fmt(c[p75Key])}`
          : "—";
      const fmtCls = (v) => (v == null ? "—" : v.toFixed(3));

      return (
        `| ${e.date.slice(0, 10)} | ${e.framework || "tanstack-start"} | ${e.stack || "stylex"} | ${commit} | ` +
        `${fmtMs(e.build?.full?.mean_ms)} | ${fmtMs(e.build?.web?.mean_ms)} | ${css} | ${js} | ${total} | ` +
        `${pair("ttfb_median", "ttfb_p75", fmtMs)} | ${pair("fcp_median", "fcp_p75", fmtMs)} | ` +
        `${pair("lcp_median", "lcp_p75", fmtMs)} | ${pair("cls_median", "cls_p75", fmtCls)} |`
      );
    })
    .join("\n");

  return `${header + rows}\n`;
}

export function createPerfEntry({
  date = new Date().toISOString(),
  framework = "tanstack-start",
  stack = "stylex",
  git = { commit: "unknown", branch: "unknown", dirty: null },
  node = process.version,
  platform = `${process.platform}/${process.arch}`,
  build = {},
  trace = null,
  assets = {},
  coldstart = null,
  profiler = null,
}) {
  return {
    date,
    framework,
    stack,
    git,
    node,
    platform,
    build,
    trace,
    assets,
    coldstart,
    profiler,
  };
}
